### ISSUE TITLE
if iverilog isn't installed, fails with cryptic error

### ISSUE THREAD

**Issue by mattvenn** [YosysHQ/mcy#8]
error given is:

Command 'export TASK=8abcbc9e-17f0-4abb-8b10-9c0e7f00e740 PRJDIR="$PWD" KEEPDIR=0 MUTATIONS="1 2 3 4 5 6 7 8 9 10";
 cd tasks/$TASK; export TASKDIR="$PWD"; exec >>logfile.txt; bash $PRJDIR/sim_simple.sh ' returned non-zero return c
ode 127.

better if dependencies were checked before running, or were listed in INSTALL or README

**Comment by nakengelhardt** [comment]
It's not really a dependency of MCY itself, just of the example testbench (which normally the user would contribute). But good point, I'll make a note to add it to the docs.

**Comment by nakengelhardt** [comment]
I've updated the readme but I'm keeping this open because I still want to check if I can improve the error message when `mcy run` is aborted by a task error.

**Comment by nakengelhardt** [comment]
I think we can consider this fixed with the "See logfile for details" message introduced in 66a018f.
